#!/usr/bin/env bash
# Displays the time from 0:01 to 12:59 in increments of one minute.
#   Displays hours from 0 to 12.
#   Displays minutes from 1 to 59.

hour=0

while [ $hour -le 12 ]
do
  echo "Hour: $hour"
  minute=1
  while [ $minute -le 59 ]
  do
    printf "%02d\n" "$minute"
    (( minute++ ))
  done
  (( hour++ ))
done
